# Detekt configuration for mpvEx

build:
  maxIssues: 0

config:
  validation: true

console-reports:
  active: true
  exclude:
    - 'NotificationReport'
    - 'FindingsReport'

style:
  active: true
  MagicNumber:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated:
      - "Preview"
  UnusedParameter:
    allowedNames: '_.*'
  MaxLineLength:
    active: false

complexity:
  active: true
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - "Composable"
    functionThreshold: 7
  LongMethod:
    ignoreAnnotated:
      - "Composable"
  CyclomaticComplexMethod:
    ignoreAnnotated:
      - "Composable"
  ComplexCondition:
    ignoreAnnotated:
      - "Composable"
    threshold: 6
  TooManyFunctions:
    active: false
  NestedBlockDepth:
    threshold: 5

performance:
  active: true

potential-bugs:
  active: true

exceptions:
  active: true
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

comments:
  active: true

# Compose rules from io.nlopez.compose.rules
Compose:
  active: true
  CompositionLocalNaming:
    active: true
  ModifierMissing:
    active: true
  PreviewPublic:
    active: true
  RememberMissing:
    active: true

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
      - "Preview"
  FunctionParameterNaming:
    parameterPattern: '(_)?[a-z][A-Za-z0-9]*'
  MatchingDeclarationName:
    active: false
  PackageNaming:
    active: false
  ClassNaming:
    active: false

empty-blocks:
  EmptyCatchBlock:
    active: false

formatting:
  active: true
  android: true
  Indentation:
    indentSize: 2
  MaximumLineLength:
    active: false
