name: make nightly

permissions:
  contents: write

on:
  schedule:
    - cron: '45 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build arm64-v8a APK
        run: ./gradlew assemblePreview -PabiFilters=arm64-v8a

      - name: Install apksigner
        run: |
          sudo apt-get update
          sudo apt-get install -y apksigner

      - name: Create dummy keystore
        run: |
          keytool -genkeypair -v \
            -keystore dummy.keystore \
            -storepass test1234 \
            -alias dummykey \
            -keypass test1234 \
            -dname "CN=Test, OU=Test, O=Test, L=Test, S=Test, C=PH" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000

      - name: Sign APK with apksigner (v2/v3)
        run: |
          apksigner sign \
            --ks dummy.keystore \
            --ks-key-alias dummykey \
            --ks-pass pass:test1234 \
            --key-pass pass:test1234 \
            --out mpvEx-arm64-v8a.apk \
            app/build/outputs/apk/preview/app-arm64-v8a-preview.apk

      - name: Verify APK signature
        run: apksigner verify mpvEx-arm64-v8a.apk

      - name: Get current date time in PH time
        id: datetime
        run: |
          # Get current time in PH timezone (UTC+8)
          PH_TIME=$(TZ='Asia/Manila' date +'%Y%m%d_%I%M%p')
          echo "filename_time=$PH_TIME" >> $GITHUB_OUTPUT

      - name: Download PlayerOverlay.kt file
        run: |
          curl -H "Accept: application/vnd.github.raw+json" \
          -o PlayerOverlay.kt \
          "https://api.github.com/repos/Tuding071/MpvEx-mod-attempt-/contents/app/src/main/java/app/marlboroadvance/mpvex/ui/player/PlayerOverlay.kt"

      - name: Create zip file with APK and Kotlin file
        run: |
          # Rename APK with date time format
          mv mpvEx-arm64-v8a.apk "mpvEx_${{ steps.datetime.outputs.filename_time }}.apk"
          
          # Create zip file containing both APK and Kotlin file
          zip "mpvEx_build_${{ steps.datetime.outputs.filename_time }}.zip" \
            "mpvEx_${{ steps.datetime.outputs.filename_time }}.apk" \
            "PlayerOverlay.kt"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mpvEx_build_${{ steps.datetime.outputs.filename_time }}.zip
          name: mpvEx-build-${{ steps.datetime.outputs.filename_time }}
